// Code generated by goctl. DO NOT EDIT.
package types

type SimpleUserInfoReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	City   string `json:"city"`
	Avatar string `json:"avatar"`
}

type UserInfoByIdReq struct {
	Id int64 `path:"id"`
}

type UserRegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	City     string `json:"city"`
	Avatar   string `json:"avatar"`
}

type UserRegisterRes struct {
	Id int64 `json:"id"`
}
